# This workflow will test build and run tests on pull requests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Build - PR

on:
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5
    
    - name: Test Build & Run Tests
      uses: miguelcolmenares/npm-auto-build@v1.1.0
      with:
        build-only: true  # Only build and test, don't commit
        command: 'build'
        build-dir: 'dist'
        node-version: '20'
    
    - name: Run Tests
      run: |
        npm ci
        npx jest --coverage
